#!/bin/sh
set -e

sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update -qq
sudo apt-get install --yes -qq gcc-6 g++-6
sudo apt-get install --yes -qq build-essential autoconf libtool gawk alien fakeroot linux-headers-$(uname -r) libaio-dev
sudo apt-get install --yes -qq zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libssl-dev
sudo apt-get install --yes -qq lcov libjemalloc-dev
#packages for tests
sudo apt-get install --yes -qq parted lsscsi ksh attr acl nfs-kernel-server fio
sudo apt-get install --yes -qq libgtest-dev cmake
sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-6 /usr/bin/g++

if [ ! -z "${GITHUB_USER_NAME}" ] && [ ! -z "${GITHUB_USER_NAME}" ];
then
    git config --global user.email $GITHUB_USER_EMAIL
    git config --global user.name $GITHUB_USER_NAME
else
    echo "No github credentials provided, will skip pushing of the release tags";
fi;
