#!/bin/sh
set -e

#sudo apt-get -qq update
  sudo apt-get install --yes -qq build-essential autoconf libtool gawk alien fakeroot linux-headers-$(uname -r) libaio-dev
  sudo apt-get install --yes -qq zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libssl-dev
  sudo apt-get install --yes -qq lcov libjemalloc-dev
#packages for tests
  sudo apt-get install --yes -qq parted lsscsi ksh attr acl nfs-kernel-server fio
  sudo apt-get install --yes -qq libgtest-dev cmake

