#!/bin/bash
#set -e

git clone https://github.com/openebs/zfs
git clone https://github.com/openebs/spl

echo "Clone Completed"

cd spl
git checkout spl-0.7.4
sh autogen.sh
./configure
make

cd ../zfs
#git checkout zfs-0.7.4
sh autogen.sh
./configure --enable-uzfs=yes --with-config=user --with-jemalloc
make

#Check for build success or failure
if [ -e cmd/zrepl/.libs/zrepl -a -e cmd/zpool/.libs/zpool -a -e cmd/zfs/.libs/zfs ]; then
  echo "Build finished; Binaries are available"
else
 echo "Build failure; Binaries are unavailable"
 exit 1
fi

