#!/bin/bash
set -e

source "image-tag"
IMAGEID=$( sudo docker images -q openebs/cstor-test:ci )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ];
then
  sudo docker login -u "${DNAME}" -p "${DPASS}";
  # Push image to docker hub
  # sudo docker push openebs/cstor-test:ci ;
  sudo docker tag ${IMAGEID} openebs/cstor-test:${CI_IMAGE_TAG}
  sudo docker push openebs/cstor-test:${CI_IMAGE_TAG};
  if [ ! -z "${TRAVIS_TAG}" ] ;
  then
    # Push with different tags if tagged as a release
    # When github is tagged with a release, then Travis will
    # set the release tag in env TRAVIS_TAG
    sudo docker tag ${IMAGEID} openebs/cstor-test:${TRAVIS_TAG}
    sudo docker push openebs/cstor-test:${TRAVIS_TAG};
    sudo docker tag ${IMAGEID} openebs/cstor-test:latest
    sudo docker push openebs/cstor-test:latest;
  fi;
  if [ ! -z "${IMAGE_TAG}" ] ;
  then
    sudo docker tag ${IMAGEID} openebs/cstor-test:${IMAGE_TAG}
    sudo docker push openebs/cstor-test:${IMAGE_TAG};
  fi;
else
  echo "No docker credentials provided. Skip uploading openebs/cstor-test:ci to docker hub";
fi;
