#!/bin/bash
set -e

source "$(dirname $0)/image-tag"
IMAGEID=$( sudo docker images -q openebs/cstor-pool:ci )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ];
then
  sudo docker login -u "${DNAME}" -p "${DPASS}";
  # Push image to docker hub
  sudo docker push openebs/cstor-pool:ci ;
  if [ ! -z "${IMAGE_TAG}" ] ;
  then
    # Push with different tags if tagged as a release
    # When github is tagged with a release, then Travis will
    # set the release tag in env IMAGE_TAG
    sudo docker tag ${IMAGEID} openebs/cstor-pool:${IMAGE_TAG}
    sudo docker push openebs/cstor-pool:${IMAGE_TAG};
    sudo docker tag ${IMAGEID} openebs/cstor-pool:latest
    sudo docker push openebs/cstor-pool:latest;
  fi;
else
  echo "No docker credentials provided. Skip uploading openebs/cstor-pool:ci to docker hub";
fi;
