#!/bin/bash
set -e

IMAGEID=$( sudo docker images -q openebs/cstor-main:ci )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  sudo docker login -u "${DNAME}" -p "${DPASS}";
  # Push image to docker hub
  sudo docker push openebs/cstor-main:ci ;
  if [ ! -z "${TRAVIS_TAG}" ] ; 
  then
    # Push with different tags if tagged as a release
    # When github is tagged with a release, then Travis will 
    # set the release tag in env TRAVIS_TAG
    sudo docker tag ${IMAGEID} openebs/cstor-main:${TRAVIS_TAG}
    sudo docker push openebs/cstor-main:${TRAVIS_TAG}; 
    sudo docker tag ${IMAGEID} openebs/cstor-main:latest
    sudo docker push openebs/cstor-main:latest; 
  fi;
else
  echo "No docker credentials provided. Skip uploading openebs/cstor-main:ci to docker hub"; 
fi;
